// Next
import type { Metadata } from "next";
// Google fonts
import { Cairo } from "next/font/google";
// Next Intl
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
// Components
import Header from "@/components/Header"
import Footer from "@/components/Footer"
// style
import "../globals.css";



export const metadata: Metadata = {
  title: "Abdullah Hasson",
  description: "Generated by create next app",
};

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

// Define the valid locales as a type
type ValidLocale = "en" | "ar";

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

    // Ensure that the incoming `locale` is valid
    const {locale} = await params;
    if (!routing.locales.includes(locale as ValidLocale)) {
      notFound();
    }
   
    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        dir={locale == "ar" ? "rtl" : "ltr"}
        className={`${cairo.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <>
            <Header locale={locale} />
            <hr />
            {children}
            <hr />
            <Footer />
          </>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}