// Next
import type { Metadata } from "next";
// Google fonts
import { Roboto, Cairo } from 'next/font/google'
// Next Intl
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
// Components
import Footer from "@/components/Footer"
// UI
// import { Toaster } from "sonner";
import Hr from "@/components/ui/hr";
// style
import "../globals.css";



export const metadata: Metadata = {
  title: "عبدالله حسون | مطور واجهة أمامية",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

const cairo = Cairo({
  weight: '400',
  subsets: ['arabic']
})

type ValidLocale = "en" | "ar";

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!routing.locales.includes(locale as ValidLocale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html
      lang={locale}
      data-theme='dark'
      className={`${roboto.className} ${cairo.className}`}
    >
      <body
        dir={locale == "ar" ? "rtl" : "ltr"}
        className={`antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
            {/* <Toaster /> */}
          <>
            {children}
            <Hr />
            <Footer />

          </>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}